spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:test}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

server:
  port: ${PORT:8080}

app:
  jwt:
    secret: ${APP_JWT_SECRET:dev-secret}
