app:
  jwt:
    secret: ${APP_JWT_SECRET:${JWT_SECRET:change-me}}

spring:
  security:
    oauth2:
      resourceserver:
        enabled: false
  jpa:
    open-in-view: false

server:
  port: ${PORT:8080}

logging:
  level:
    org.flywaydb: off

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    open-in-view: true
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false

app:
  jwt:
    secret: test-secret

server:
  port: 0

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${SPRING_DATASOURCE_URL:${JDBC_DATABASE_URL:${DATABASE_URL:}}}
    username: ${SPRING_DATASOURCE_USERNAME:${JDBC_DATABASE_USERNAME:}}
    password: ${SPRING_DATASOURCE_PASSWORD:${JDBC_DATABASE_PASSWORD:}}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
